### ISSUE TITLE
I think the battle list could improve

### ISSUE THREAD

**Issue by kokekanon** [OTAcademy/otclientv8#3]
I've always found the v8 battle to be "weird" I'm used to the CipSoft client where if a player or monster appears in the battle list it appears last.

In the video I demonstrate that sometimes the players does not appear at the end.

video context:
I make the comparison of 3 battle list
1.- V8 most recent release OTacademy
2.- Mehah
3.- ClientCipSoft

The player who pointed with an arrow "[DNT] Freekendy" was in a war (far of temple), he died and appeared in the thais temple.
I am with 3 mc in the same SQM
the moment "[DNT] Freekendy" appears in my range,

V8 orders it to the "middle" of the battlelist❌ 
Mehah at the end of the battlelist                ✅ 
CipSoft at the end of the battle list             ✅ 

In a server war, the battle list is essential, since I always end up targeting the wrong person.because v8 sometimes orders them incorrectly

V8           configured   Total Age | Asc.
Mehah  configured          Age     | Asc.
CipSoft                             default

unfortunately my c++ level is very low
Try to include the missing c++ functions to make the other game_battle (binary trees battlelist of user "andersonfaaria" or  old of "andrefaramir, BeniS [i think]")  modules compatible in v8 but i don't have the knowledge xd 

https://user-images.githubusercontent.com/114332266/222044430-b4858fd8-19a6-4792-8f8d-55dd786c06ee.mp4

//////////////////////////////////
.
.
.
Bug 2 : Crazy Battle list in OTCv8  IN Screen-age

https://user-images.githubusercontent.com/114332266/222044768-207a6b1f-4592-427b-a1de-b191e983ab2c.mp4

the battle list is essential in server war
I am in the same sqm in OTCv8 client and Old client
but for some reason, he goes crazy

OTCv8 filter in
**Screen-age | ASC**
server 8.60 war 
default module otcv8

**Comment by Nottinghster** [comment]
@Zbizu @kokekanon @Oen44 

Any news or intention to fix this?

**Comment by kokekanon** [comment]
It will be almost a year since the publication of this issue.

 12 months without any activity, 
 
 so I will close the issue. 
 
 Personally, I switched to Mehah where this bug does not exist.
